### PR TITLE
Patch missing or useless files.

### PR DESCRIPTION
**Pull request by ar-cyber**

### CODE REVIEW

**Comment by SethBurkart123** [comment]
the `env.submit.example` doesn't get filled out. I have in the `.gitignore` the actual file that gets the values filled out for uploading. So that file is safe.

**Comment by ar-cyber** [comment]
So that means the file can be deleted?

**Comment by SethBurkart123** [comment]
It needs to stay as an example so that people know what fields to fill out int the actual `.env.submit`

**Review by Crazypersonalph — CHANGES_REQUESTED** [review]
We'll keep the example environment file, as it is, well, an example.
Otherwise it looks good.

**Comment by ar-cyber** [comment]
its been updated

**Review by Crazypersonalph — APPROVED** [review]
Looks good 👍

**Pull request merged**
