### PR TITLE
Added Discord icon

### PR DESCRIPTION
**Pull request by MEGA-Dawg68**
I added a discord icon for the support section on the Whats new page.
It was really a reminder as the icon a bit cooked...
image

I am hopeless with svg, so if you want to fix it go ahead.

:)

### CODE REVIEW

**Comment by ar-cyber** [comment]
ITS CURSED. USE MODULES!!!

**Comment by MEGA-Dawg68** [comment]
😥
I got no clue what you mean by that. I ain't that good at any of this
________________________________

**Comment by SethBurkart123** [comment]
Yeah, I might just drop in and fix it for you sometime soon (then merge it- because that's a good addition)

**Comment by ar-cyber** [comment]
@SethBurkart123 Would you use SVG or use another module to add svelte icons.

**Comment by SethBurkart123** [comment]
> @SethBurkart123 Would you use SVG or use another module to add svelte icons.

Well we do use svgs for the other ones. When i'm mounting ui elements, if I have an icon for it in the pack then I use that, otherwise I use svgs.

**Comment by SethBurkart123** [comment]
Thanks so much! I've fixed it up and it's all in!

PS: all I had to change was the viewbox from "0 0 24 24" to "0 0 16 16"

**Pull request merged**
