### PR TITLE
Change Settings UI to svelte under the hood

### PR DESCRIPTION
**Pull request by SethBurkart123**
- [x] Move to Shadow DOM
- [x] Implement settings UI in svelte
- [x] Display backgrounds
- [x] Add themes
- [x] Theme store
- [x] Background migration logic

### CODE REVIEW

**Comment by ar-cyber** [comment]
wow lots of progress on this one, probably.

**Comment by ar-cyber** [comment]
it looks really good but some of the scaling needs to be fixed, and the scrollbar is a little bit weird.

**Comment by Crazypersonalph** [comment]
We can't merge this until we figure out what it causing the Firefox bug that breaks the popup, whether it is a Svelte Beta issue or a project issue.

**Comment by Crazypersonalph** [comment]
Test for webhook

**Comment by Crazypersonalph** [comment]
comment

**Comment by Crazypersonalph** [comment]
comment

**Comment by ar-cyber** [comment]
We're over 100 commits!

**Comment by SethBurkart123** [comment]
Update: store now contains a bunch of images. Videos currently aren't available as I haven't indexed any on the repository.

**Comment by ar-cyber** [comment]
Firefox is still broken (missing icons and broken scrollbars)

**Comment by ar-cyber** [comment]
Actually these issues are present on chrome as well.

**Comment by SethBurkart123** [comment]
With migration added we are ready to merge :)

**Pull request merged**
