### PR TITLE
add debug messages

### PR DESCRIPTION
**Pull request by ar-cyber**

### CODE REVIEW

**Comment by SethBurkart123** [comment]
I think it would probably be better to make that one a `console.debug` statement so that visibility of it can be toggled in the console menu.

**Review by SethBurkart123 — COMMENTED** [review]
Change the `console.log` to a `console.debug` so that the messages can be easily toggled.

**Review by SethBurkart123 — CHANGES_REQUESTED** [review]
Change the `console.log` to a `console.debug` so that the messages can be easily toggled.

**Comment by ar-cyber** [comment]
ok

**Comment by ar-cyber** [comment]
> Change the `console.log` to a `console.debug` so that the messages can be easily toggled.

console.debug outputs nothing

**Comment by ar-cyber** [comment]
updated all to make them use console.info, which is much better

**Review by Crazypersonalph — APPROVED** [review]
Looks good, also maybe check in other files and functions whether they use logging.

**Comment by ar-cyber** [comment]
ok

**Comment by Crazypersonalph** [comment]
> > Change the `console.log` to a `console.debug` so that the messages can be easily toggled.
> 
> console.debug outputs nothing

You need to change log level in DevTools.

**Comment by ar-cyber** [comment]
> > > Change the `console.log` to a `console.debug` so that the messages can be easily toggled.
> > 
> > 
> > console.debug outputs nothing
> 
> You need to change log level in DevTools.

ah. I'll still use ```console.info``` because it looks nicer in DevTools

**Review by SethBurkart123 — APPROVED** [review]

**Pull request merged**
