### PR TITLE
ar-cyber svelte patches

### PR DESCRIPTION
**Pull request by ar-cyber**
Scaling a bit broken but it's not only this menu.

### CODE REVIEW

**Review by Crazypersonalph — APPROVED** [review]
Looks good to be merged

**Comment by Crazypersonalph** [comment]
@SethBurkart123 Please check if CSS code that was removed is actually redundant.

**Comment by ar-cyber** [comment]
> @SethBurkart123 Please check if CSS code that was removed is actually redundant.

it seems to work, the line was commented because the build said it was unused and it doesn't seem to impact anything.

**Comment by SethBurkart123** [comment]
Looks good! Thanks so much.

**Pull request merged**
